services:
  books-api:
    container_name: books-api
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/images/main/prod.Dockerfile
#    image: some-artifactiry-place.com/books-api:latest
    volumes:
      - .env:/var/www/html/.env:rw
      - ./api/storage/:/var/www/html/storage:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booksapi.tls=true"
      - "traefik.http.routers.booksapi.entrypoints=websecure"
      - "traefik.http.routers.booksapi.rule=Host(`sometestnewdomain.co.uk`)"
      - "traefik.http.services.booksapi.loadbalancer.server.port=8080"
      - "traefik.http.routers.booksapi.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik-net"
    networks:
      - traefik-net

  redis:
    image: redis:alpine
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - traefik-net

networks:
  default_network:
    driver: bridge
  traefik-net:
    external: true
