name: CI Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - 'release/**'
      - 'feature/**'
      - 'master'

jobs:
  composer-validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-versions: [ '8.3' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, curl, json, openssl

      - name: Validate composer.json and composer.lock
        working-directory: ./api
        run: composer validate

  code-style-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-versions: [ '8.3' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, curl, json, openssl

      - name: Get PHP version
        run: php -v

      - name: Run Laravel Pint code style check
        working-directory: ./api
        run: composer require laravel/pint --dev && ./vendor/bin/pint --test

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-versions: [ '8.3' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, curl, json, openssl

      - name: Get PHP version
        run: php -v

      - name: Get Composer Cache Directory
        working-directory: ./api
        id: composer-cache
        run: echo "COMPOSER_DIR=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.COMPOSER_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        working-directory: ./api
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        working-directory: ./api
        run: php artisan test
